import fs from 'node:fs';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';
const root=new URL('../src/',import.meta.url),dom=new JSDOM(fs.readFileSync(new URL('index.html',root),'utf8'),{url:'https://example.test'});
const ids=[...dom.window.document.querySelectorAll('[id]')].map(n=>n.id);assert.equal(new Set(ids).size,ids.length);
globalThis.document=dom.window.document;globalThis.window=dom.window;globalThis.confirm=()=>true;
const dialog=document.getElementById('detailDialog');dialog.showModal=()=>dialog.open=true;dialog.close=()=>dialog.open=false;
dom.window.HTMLElement.prototype.scrollIntoView=()=>{};
const application={user_id:crypto.randomUUID(),full_name:'<script>Captain</script>',phone:'07700000004',chassis:'ABC123',color:'أحمر',model:'2026',status:'pending',revision:1,documents:Object.fromEntries(['id_front','id_back','residence_front','residence_back','portrait'].map(k=>[k,k+'.jpg']))};
let checks=1,calls=[],markerPoints=[],chatRows=[{id:'1',body:'Hello',is_admin:false,created_at:new Date().toISOString()}];
const user={user_id:crypto.randomUUID(),name:'<img src=x onerror=alert(1)>',phone:'07700000001',captain:false,blocked:false};
const ride={id:crypto.randomUUID(),status:'accepted',fare:1500,discount:0,customer_due:1500,distance_m:1200,pickup:[33.54,44.4],destination:[33.55,44.41],rider_name:user.name,created_at:new Date().toISOString(),geometry:{type:'LineString',coordinates:[[44.4,33.54],[44.41,33.55]]}};
const captain={user_id:crypto.randomUUID(),name:'Captain',phone:'07700000003',captain:true,online:true,lat:33.541,lng:44.401,location_at:new Date().toISOString()};
const stats={server_now:new Date().toISOString(),users:1,captains:1,online:1,active_rides:1,today_rides:1,today_completed:1500,applications:0,worker:{heartbeat:new Date().toISOString()}};
const results={overview:stats,users:[user],rides:[ride],track:{ride,captain,offers:[],server_now:stats.server_now},finance:{wallets:[{...user,balance:5000}],coupons:[{code:'TEST',amount:500,active:true,max_uses:100,expires_at:stats.server_now}],rooms:[]},ledger:{balance:5000,entries:[],payments:[]},favorites:[{id:crypto.randomUUID(),user_id:user.user_id,label:'House',lat:33.54,lng:44.4,name:user.name,phone:user.phone}],recovery:[{id:crypto.randomUUID(),phone:user.phone,name:user.name,created_at:stats.server_now}],support_rooms:[{...user,unread:2,last_at:stats.server_now}],security:[{phone:user.phone,failures:3,requests:3,window_at:stats.server_now}],audit:[],archives:[]};
const db={storage:{from:()=>({createSignedUrl:async path=>({data:{signedUrl:'https://private.test/'+path},error:null})})},rpc:async(name,{p_action,p_data})=>{calls.push({name,op:p_action,data:p_data});if(name==='tkt_captain_registration'){if(p_action==='list')return {data:[application],error:null};if(p_action==='review'){application.status=p_data.decision;application.reason=p_data.reason;return {data:application,error:null}}}return {data:['read','recovery_messages'].includes(p_action)?chatRows:results[p_action]??{ok:true},error:null}},from:()=>({select(){return this},eq(){return this},limit:async()=>({data:[captain],error:null})}),auth:{getSession:async()=>({data:{session:null}})}};
globalThis.mockCreateClient=()=>db;
const layer=()=>({addTo(){return this},clearLayers(){},bindPopup(){return this},on(){return this},setLatLng(){return this}});
globalThis.L={map:()=>({setView(){return this},fitBounds(){},invalidateSize(){},remove(){},on(){},removeLayer(){}}),tileLayer:layer,layerGroup:layer,polygon:layer,divIcon:()=>({}),circleMarker:layer,marker:p=>{markerPoints.push(p);return layer()},geoJSON:()=>({...layer(),getBounds:()=>({isValid:()=>true,getSouthWest:()=>[33.54,44.4],getNorthEast:()=>[33.55,44.41]})})};
let source=fs.readFileSync(new URL('app.js',root),'utf8').replace(/^import .*;\n/,'const createClient=globalThis.mockCreateClient;\n');
const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
const app=await new AsyncFunction(source+'\nreturn {loadOverview,loadRides,loadUsers,loadFinance,loadSupport,loadFavorites,loadSecurity,loadAudit,trackRide,updateTrack,chat,updateChat,closeDetail,showPage,manage,archive,loadApplications,applicationDetail};')();
const eq=(a,b)=>{assert.deepEqual(a,b);checks++};
for(const page of ['overview','rides','users','finance','support','favorites','security','audit','coverage','pricing','applications']){app.showPage(page);eq(document.querySelectorAll('.page:not([hidden])').length,1);}
await app.loadOverview();eq(document.getElementById('metrics').children.length,7);eq(markerPoints.at(-1),[captain.lat,captain.lng]);
await app.loadUsers();eq(document.getElementById('userList').querySelectorAll('img').length,0);eq(document.getElementById('userList').textContent.includes(user.name),true);
await app.loadRides();eq(document.getElementById('rideList').textContent.includes('التفاصيل والتتبع'),true);eq(document.getElementById('rideList').textContent.includes('إلغاء الرحلة'),true);
await app.loadFinance();eq(document.getElementById('walletList').textContent.includes('شحن المحفظة'),true);eq(document.getElementById('couponList').textContent.includes('TEST'),true);
await app.loadSupport();eq(document.getElementById('recoveryRooms').textContent.includes('تعيين كلمة سر'),true);
await app.loadFavorites();eq(document.getElementById('favoriteList').textContent.includes('House'),true);
await app.loadSecurity();eq(document.getElementById('securityList').textContent.includes('فتح المحاولات'),true);
await app.trackRide(ride.id);eq(markerPoints.at(-1),[captain.lat,captain.lng]);captain.lat=33.542;await app.updateTrack();eq(markerPoints.at(-1),[33.542,captain.lng]);
await app.chat('recovery',results.recovery[0]);document.getElementById('chatInput').value='unfinished reply';chatRows=[...chatRows,{id:'2',body:'New message',is_admin:false,created_at:stats.server_now}];await app.updateChat();eq(document.getElementById('chatInput').value,'unfinished reply');eq(document.getElementById('chatLog').children.length,2);
await app.archive('recovery',results.recovery[0].id);eq(calls.some(c=>c.op==='archive'&&c.data.kind==='recovery'),true);
eq(calls.every(c=>['tkt_manage','tkt_captain_registration'].includes(c.name)),true);
await app.loadApplications();eq(document.getElementById('applicationList').querySelectorAll('script').length,0);eq(document.getElementById('applicationList').textContent.includes(application.full_name),true);
await app.applicationDetail(application);eq(document.querySelectorAll('.application-documents img').length,5);eq(document.getElementById('detailBody').querySelectorAll('script').length,0);
const reject=[...document.querySelectorAll('#detailBody button')].find(b=>b.textContent==='رفض لغرض التعديل');await reject.onclick();eq(calls.some(c=>c.op==='review'),false);eq(document.getElementById('status').textContent.includes('سبب'),true);
document.getElementById('applicationReason').value='أعد تصوير الجنسية';await reject.onclick();eq(calls.find(c=>c.op==='review').data.reason,'أعد تصوير الجنسية');eq(application.status,'changes_required');eq(dialog.open,false);
application.status='pending';await app.applicationDetail(application);await [...document.querySelectorAll('#detailBody button')].find(b=>b.textContent==='موافقة وتفعيل الكابتن').onclick();eq(application.status,'approved');eq(calls.at(-2).data.revision,1);
app.closeDetail();dom.window.close();console.log(`${checks} dashboard DOM, tracking and support interaction checks passed`);
